[build]
builder = "nixpacks"

[build.nixpacksConfig]
buildCmd = "cd backend && npm install"
startCmd = "cd backend && node app.js"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"